require_relative 'config/environment'
include ActiveRecord::Tasks
require 'sinatra/activerecord/rake'

desc "Loads a console"
task :console do
    Pry.start
end

desc "Say Hello to Mod1"
task :say_hi do
    puts "Hello Mod One!"
end

desc "Sets up the database"
task :set_up_db do 
    author_sql = <<-SQL
        CREATE TABLE IF NOT EXISTS authors (
            id INTEGER PRIMARY KEY,
            name TEXT
            );
    SQL

    book_sql = <<-SQL
        CREATE TABLE IF NOT EXISTS books (
            id INTEGER PRIMARY KEY,
            title TEXT,
            author_id INTEGER
        );
    SQL

    DB.execute(author_sql)
    DB.execute(book_sql)

end